### ISSUE TITLE
2 issues with stop

### ISSUE THREAD

**Issue by CommodoreST** [Maxstupo/ydl-ui#113] opened 2023-04-28 09:55 UTC
**Describe the bug**
1. Stop doesn't really stop. It still downloads file in the background. When I open log it's clear to see it's still downloading.
2. Sometimes it crashes YDL-UI after I try to stop downloading a file.

**Expected behavior**
Immediate stop. Instant terminate/kill youtube downloader if needed.

**Information (please complete the following information)**
 - ytdl-patched-red.exe - https://github.com/ytdl-patched/ytdl-patched
 - Windows 10 x64

**Comment by Maxstupo** [comment] 2024-01-03 15:59
This is most likely something to do with `ytdl-patched` refusing to close. `Stop` in ydl-ui forces the download process to close (see [here](https://github.com/Maxstupo/ydl-ui/blob/abb31f862e0c04765d821d8dbddc0ffd7a59617f/YDL-UI/Utility/ExecutableProcess.cs#L67-L74C10)).

If you are using a custom downloader for ytdl-patched such as `aria2`, that also might be the cause.

Closing, since nothing can really be done within ydl-ui.

**Closed by Maxstupo** 2024-01-03 15:59 UTC

**Comment by Mishasama** [comment] 2025-07-21 00:55
@Maxstupo Same problem with the offcial yt-dlp

**Comment by ZX-Commodore-ST** [comment] 2025-07-29 14:42
Yes, it shouldn't be marked as completed.
